//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PenguinTools.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PenguinTools.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send it to the developer if you don&apos;t understand..
        /// </summary>
        public static string Alert_Diagnostic_report {
            get {
                return ResourceManager.GetString("Alert_Diagnostic_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please edit the properties of charts in Margrete first..
        /// </summary>
        public static string Alert_Edit_notice {
            get {
                return ResourceManager.GetString("Alert_Edit_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file has been modified on {0:HH:mm:ss}. Reload to use the latest version..
        /// </summary>
        public static string Alert_File_changed {
            get {
                return ResourceManager.GetString("Alert_File_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Button_Clear {
            get {
                return ResourceManager.GetString("Button_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string Button_Convert {
            get {
                return ResourceManager.GetString("Button_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Button_Copy {
            get {
                return ResourceManager.GetString("Button_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Exception.
        /// </summary>
        public static string Button_Copy_Exception {
            get {
                return ResourceManager.GetString("Button_Copy_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract *.dds from *.afb.
        /// </summary>
        public static string Button_Extract_dds_from_afb {
            get {
                return ResourceManager.GetString("Button_Extract_dds_from_afb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Button_Generate {
            get {
                return ResourceManager.GetString("Button_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Button_Help {
            get {
                return ResourceManager.GetString("Button_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Temp Directory.
        /// </summary>
        public static string Button_Open_temp_directory {
            get {
                return ResourceManager.GetString("Button_Open_temp_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recollect Game Assets.
        /// </summary>
        public static string Button_Recollect_A000 {
            get {
                return ResourceManager.GetString("Button_Recollect_A000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Button_Reload {
            get {
                return ResourceManager.GetString("Button_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BGM.
        /// </summary>
        public static string Category_BGM {
            get {
                return ResourceManager.GetString("Category_BGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string Category_Chart {
            get {
                return ResourceManager.GetString("Category_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string Category_Display {
            get {
                return ResourceManager.GetString("Category_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        public static string Category_Misc {
            get {
                return ResourceManager.GetString("Category_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Category_Settings {
            get {
                return ResourceManager.GetString("Category_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song.
        /// </summary>
        public static string Category_Song {
            get {
                return ResourceManager.GetString("Category_Song", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string Category_Sync {
            get {
                return ResourceManager.GetString("Category_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field determines the background stage in the game. To quickly set it up, include &quot;#meta stage [StringID]&quot; in the chart comment (Replace [StringID] with the stage&apos;s ID or name)..
        /// </summary>
        public static string Description_BackgroundStage {
            get {
                return ResourceManager.GetString("Description_BackgroundStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To reduce the audio latency discrepancy between the game and Margrete, it is recommended to prioritize using .wav or .ogg audio files with a sample rate of 48000Hz..
        /// </summary>
        public static string Description_BgmFile {
            get {
                return ResourceManager.GetString("Description_BgmFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the starting BPM (Beats Per Minute) of the chart. It is used to calculate real offset..
        /// </summary>
        public static string Description_BgmInitialBpm {
            get {
                return ResourceManager.GetString("Description_BgmInitialBpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the time signature (beats per bar and note value) at the start of the chart. It is used to calculate real offset..
        /// </summary>
        public static string Description_BgmInitialTimeSignature {
            get {
                return ResourceManager.GetString("Description_BgmInitialTimeSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM displayed in song selection menu.
        /// </summary>
        public static string Description_DisplayBPM {
            get {
                return ResourceManager.GetString("Description_DisplayBPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To quickly set it up, include &quot;#meta genre [StringID]&quot; in the chart comment (Replace [StringID] with the stage&apos;s ID or name)..
        /// </summary>
        public static string Description_Genre {
            get {
                return ResourceManager.GetString("Description_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure this through Margrete (Insert a blank bar before the first measure). If enabled, a silent measure with click cues is inserted at the beginning, ensuring that the first musical measure follows the blank..
        /// </summary>
        public static string Description_InsertBlankMeasure {
            get {
                return ResourceManager.GetString("Description_InsertBlankMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to specify which difficulty&apos;s chart property will be used as the base reference..
        /// </summary>
        public static string Description_MainDifficulty {
            get {
                return ResourceManager.GetString("Description_MainDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure this through Margrete (Base timeline). Determines which Timeline affects the bar line positions and AIR animation speed. Default is 0..
        /// </summary>
        public static string Description_MainTil {
            get {
                return ResourceManager.GetString("Description_MainTil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure this through Margrete. This value represents the offset (in seconds) applied to the song manually set by user. Positive values indicate a delay, while negative values indicate an advance..
        /// </summary>
        public static string Description_ManualOffset {
            get {
                return ResourceManager.GetString("Description_ManualOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value represents the calculated offset (in seconds) applied to the song. Positive values indicate a delay, while negative values indicate an advance..
        /// </summary>
        public static string Description_RealOffset {
            get {
                return ResourceManager.GetString("Description_RealOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Song ID is extracted from Margrete&apos;s Song ID..
        /// </summary>
        public static string Description_SongId {
            get {
                return ResourceManager.GetString("Description_SongId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines how songs are sorted in the game..
        /// </summary>
        public static string Description_SortName {
            get {
                return ResourceManager.GetString("Description_SortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event that unlocks the &quot;World&apos;s End&quot; or &quot;ULTIMA&quot; chart in the game. If left blank, the generation of the associated Event.xml file will be skipped..
        /// </summary>
        public static string Description_UnlockEventID {
            get {
                return ResourceManager.GetString("Description_UnlockEventID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event that unlocks the &quot;World&apos;s End&quot; or &quot;ULTIMA&quot; charts in the game..
        /// </summary>
        public static string Description_UnlockEventIDOption {
            get {
                return ResourceManager.GetString("Description_UnlockEventIDOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string Display_Artist {
            get {
                return ResourceManager.GetString("Display_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background File.
        /// </summary>
        public static string Display_BackgroundFile {
            get {
                return ResourceManager.GetString("Display_BackgroundFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Stage.
        /// </summary>
        public static string Display_BackgroundStage {
            get {
                return ResourceManager.GetString("Display_BackgroundStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Process Size.
        /// </summary>
        public static string Display_BatchSize {
            get {
                return ResourceManager.GetString("Display_BatchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BGM File.
        /// </summary>
        public static string Display_BgmFile {
            get {
                return ResourceManager.GetString("Display_BgmFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial BPM.
        /// </summary>
        public static string Display_BgmInitialBpm {
            get {
                return ResourceManager.GetString("Display_BgmInitialBpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Time Signature.
        /// </summary>
        public static string Display_BgmInitialTimeSignature {
            get {
                return ResourceManager.GetString("Display_BgmInitialTimeSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Start Time (s).
        /// </summary>
        public static string Display_BgmPreviewStart {
            get {
                return ResourceManager.GetString("Display_BgmPreviewStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Stop Time (s).
        /// </summary>
        public static string Display_BgmPreviewStop {
            get {
                return ResourceManager.GetString("Display_BgmPreviewStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Audio.
        /// </summary>
        public static string Display_ConvertAudio {
            get {
                return ResourceManager.GetString("Display_ConvertAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Background.
        /// </summary>
        public static string Display_ConvertBackground {
            get {
                return ResourceManager.GetString("Display_ConvertBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Chart.
        /// </summary>
        public static string Display_ConvertChart {
            get {
                return ResourceManager.GetString("Display_ConvertChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Jacket.
        /// </summary>
        public static string Display_ConvertJacket {
            get {
                return ResourceManager.GetString("Display_ConvertJacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denominator.
        /// </summary>
        public static string Display_Denominator {
            get {
                return ResourceManager.GetString("Display_Denominator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designer.
        /// </summary>
        public static string Display_Designer {
            get {
                return ResourceManager.GetString("Display_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string Display_Difficulty {
            get {
                return ResourceManager.GetString("Display_Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display BPM.
        /// </summary>
        public static string Display_DisplayBPM {
            get {
                return ResourceManager.GetString("Display_DisplayBPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        public static string Display_FilePath {
            get {
                return ResourceManager.GetString("Display_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Event.xml.
        /// </summary>
        public static string Display_GenerateEventXml {
            get {
                return ResourceManager.GetString("Display_GenerateEventXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Display_Genre {
            get {
                return ResourceManager.GetString("Display_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Blank Measure.
        /// </summary>
        public static string Display_InsertBlankMeasure {
            get {
                return ResourceManager.GetString("Display_InsertBlankMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Background.
        /// </summary>
        public static string Display_IsCustomStage {
            get {
                return ResourceManager.GetString("Display_IsCustomStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jacket File.
        /// </summary>
        public static string Display_JacketFile {
            get {
                return ResourceManager.GetString("Display_JacketFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Display_Level {
            get {
                return ResourceManager.GetString("Display_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baseline Difficulty.
        /// </summary>
        public static string Display_MainDifficulty {
            get {
                return ResourceManager.GetString("Display_MainDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Timeline.
        /// </summary>
        public static string Display_MainTil {
            get {
                return ResourceManager.GetString("Display_MainTil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Offset (s).
        /// </summary>
        public static string Display_ManualOffset {
            get {
                return ResourceManager.GetString("Display_ManualOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes Field Line Color.
        /// </summary>
        public static string Display_NotesFieldLine {
            get {
                return ResourceManager.GetString("Display_NotesFieldLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerator.
        /// </summary>
        public static string Display_Numerator {
            get {
                return ResourceManager.GetString("Display_Numerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Name.
        /// </summary>
        public static string Display_OptionName {
            get {
                return ResourceManager.GetString("Display_OptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Offset (s).
        /// </summary>
        public static string Display_RealOffset {
            get {
                return ResourceManager.GetString("Display_RealOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string Display_ReleaseDate {
            get {
                return ResourceManager.GetString("Display_ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate ReleaseTag.xml.
        /// </summary>
        public static string Display_ReleaseTagXml {
            get {
                return ResourceManager.GetString("Display_ReleaseTagXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song ID.
        /// </summary>
        public static string Display_SongId {
            get {
                return ResourceManager.GetString("Display_SongId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Name.
        /// </summary>
        public static string Display_SortName {
            get {
                return ResourceManager.GetString("Display_SortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage ID.
        /// </summary>
        public static string Display_StageId {
            get {
                return ResourceManager.GetString("Display_StageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Display_Title {
            get {
                return ResourceManager.GetString("Display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Ultima Event ID.
        /// </summary>
        public static string Display_UltimaEventId {
            get {
                return ResourceManager.GetString("Display_UltimaEventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Event ID.
        /// </summary>
        public static string Display_UnlockEventID {
            get {
                return ResourceManager.GetString("Display_UnlockEventID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock World&apos;s End Event ID.
        /// </summary>
        public static string Display_WeEventId {
            get {
                return ResourceManager.GetString("Display_WeEventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World&apos;s End Difficulty.
        /// </summary>
        public static string Display_WorldsEndDifficulty {
            get {
                return ResourceManager.GetString("Display_WorldsEndDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World&apos;s End Tag.
        /// </summary>
        public static string Display_WorldsEndTag {
            get {
                return ResourceManager.GetString("Display_WorldsEndTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified audio file was not found..
        /// </summary>
        public static string Error_Audio_file_not_found {
            get {
                return ResourceManager.GetString("Error_Audio_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported audio format. Only wav (pcm_s16le at 48,000 Hz) is supported..
        /// </summary>
        public static string Error_Audio_format_not_supported {
            get {
                return ResourceManager.GetString("Error_Audio_format_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background File is not set..
        /// </summary>
        public static string Error_Background_file_is_not_set {
            get {
                return ResourceManager.GetString("Error_Background_file_is_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified background image file was not found..
        /// </summary>
        public static string Error_Background_file_not_found {
            get {
                return ResourceManager.GetString("Error_Background_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command execution failed..
        /// </summary>
        public static string Error_Command_failed {
            get {
                return ResourceManager.GetString("Error_Command_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified background effect file was not found..
        /// </summary>
        public static string Error_Effect_file_not_found {
            get {
                return ResourceManager.GetString("Error_Effect_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is ignored since Song ID is missing. Set a number for Song Id in Margrete..
        /// </summary>
        public static string Error_File_ignored_due_to_id_missing {
            get {
                return ResourceManager.GetString("Error_File_ignored_due_to_id_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file was not found..
        /// </summary>
        public static string Error_File_not_found {
            get {
                return ResourceManager.GetString("Error_File_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid audio format..
        /// </summary>
        public static string Error_Invalid_audio {
            get {
                return ResourceManager.GetString("Error_Invalid_audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid effect image format..
        /// </summary>
        public static string Error_Invalid_bg_fx_image {
            get {
                return ResourceManager.GetString("Error_Invalid_bg_fx_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid background image format..
        /// </summary>
        public static string Error_Invalid_bg_image {
            get {
                return ResourceManager.GetString("Error_Invalid_bg_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The header {0} in the chart file does not match {1}..
        /// </summary>
        public static string Error_Invalid_Header {
            get {
                return ResourceManager.GetString("Error_Invalid_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid jacket image format..
        /// </summary>
        public static string Error_Invalid_jk_image {
            get {
                return ResourceManager.GetString("Error_Invalid_jk_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified jacket file was not found..
        /// </summary>
        public static string Error_Jacket_file_not_found {
            get {
                return ResourceManager.GetString("Error_Jacket_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No charts are found in the directory..
        /// </summary>
        public static string Error_No_charts_are_found_directory {
            get {
                return ResourceManager.GetString("Error_No_charts_are_found_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * But nobody came..
        /// </summary>
        public static string Error_Noop {
            get {
                return ResourceManager.GetString("Error_Noop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled: {0}..
        /// </summary>
        public static string Error_Operation_cancelled_for {
            get {
                return ResourceManager.GetString("Error_Operation_cancelled_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The preview stop time must be greater than the start time..
        /// </summary>
        public static string Error_Preview_stop_greater_than_start {
            get {
                return ResourceManager.GetString("Error_Preview_stop_greater_than_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected to read {0} bytes for {1} but only got {2}..
        /// </summary>
        public static string Error_Size_Incompatible {
            get {
                return ResourceManager.GetString("Error_Size_Incompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song ID is not set..
        /// </summary>
        public static string Error_Song_id_is_not_set {
            get {
                return ResourceManager.GetString("Error_Song_id_is_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage ID is not set..
        /// </summary>
        public static string Error_Stage_id_is_not_set {
            get {
                return ResourceManager.GetString("Error_Stage_id_is_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Error_Unhandled {
            get {
                return ResourceManager.GetString("Error_Unhandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afb Texture (*.afb)|*.afb.
        /// </summary>
        public static string Filefilter_afb {
            get {
                return ResourceManager.GetString("Filefilter_afb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chunithm Chart (*.c2s)|*.c2s.
        /// </summary>
        public static string Filefilter_c2s {
            get {
                return ResourceManager.GetString("Filefilter_c2s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectDraw Surface (*.dds)|*.dds.
        /// </summary>
        public static string Filefilter_dds {
            get {
                return ResourceManager.GetString("Filefilter_dds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable (*.exe)|*.exe.
        /// </summary>
        public static string Filefilter_exe {
            get {
                return ResourceManager.GetString("Filefilter_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files (*.png;*.jpg;*.jpeg;*.webp)|*.png;*.jpg;*.jpeg;*.webp.
        /// </summary>
        public static string Filefilter_image {
            get {
                return ResourceManager.GetString("Filefilter_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margrete Chart (*.mgxc)|*.mgxc.
        /// </summary>
        public static string Filefilter_mgxc {
            get {
                return ResourceManager.GetString("Filefilter_mgxc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Files (*.wav;*.ogg;*.mp3)|*.wav;*.ogg;*.mp3.
        /// </summary>
        public static string Filefilter_sound {
            get {
                return ResourceManager.GetString("Filefilter_sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview {0} time ({1:F3} s) exceeds the maximum value ({2:F3} s) and has been clamped to prevent overflow..
        /// </summary>
        public static string Hint_Preview_value_clamped {
            get {
                return ResourceManager.GetString("Hint_Preview_value_clamped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio: .
        /// </summary>
        public static string Label_Audio {
            get {
                return ResourceManager.GetString("Label_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background (1920×1080): .
        /// </summary>
        public static string Label_Background {
            get {
                return ResourceManager.GetString("Label_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart: .
        /// </summary>
        public static string Label_Chart {
            get {
                return ResourceManager.GetString("Label_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Label_Details {
            get {
                return ResourceManager.GetString("Label_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects (256×256).
        /// </summary>
        public static string Label_Effects {
            get {
                return ResourceManager.GetString("Label_Effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder: .
        /// </summary>
        public static string Label_Folder {
            get {
                return ResourceManager.GetString("Label_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image: .
        /// </summary>
        public static string Label_Image {
            get {
                return ResourceManager.GetString("Label_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jacket ID.
        /// </summary>
        public static string Label_Jacket_ID {
            get {
                return ResourceManager.GetString("Label_Jacket_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Label_Message {
            get {
                return ResourceManager.GetString("Label_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        public static string Label_Not_Available {
            get {
                return ResourceManager.GetString("Label_Not_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes Field Line Color.
        /// </summary>
        public static string Label_NotesField_Line_Color {
            get {
                return ResourceManager.GetString("Label_NotesField_Line_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Label_Parameters {
            get {
                return ResourceManager.GetString("Label_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Label_Path {
            get {
                return ResourceManager.GetString("Label_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Label_Preview {
            get {
                return ResourceManager.GetString("Label_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Label_Properties {
            get {
                return ResourceManager.GetString("Label_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Label_Settings {
            get {
                return ResourceManager.GetString("Label_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage ID.
        /// </summary>
        public static string Label_Stage_ID {
            get {
                return ResourceManager.GetString("Label_Stage_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Label_Time {
            get {
                return ResourceManager.GetString("Label_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Foahh/PenguinTools/wiki/%E4%B8%AD%E6%96%87.
        /// </summary>
        public static string Link_Documentation {
            get {
                return ResourceManager.GetString("Link_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different EX effects coexist at the same tick: {0}. The game will only display one of these..
        /// </summary>
        public static string Mg_Concurrent_ex_effects {
            get {
                return ResourceManager.GetString("Mg_Concurrent_ex_effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No BPM change event was found at tick 0..
        /// </summary>
        public static string Mg_Head_BPM_not_found {
            get {
                return ResourceManager.GetString("Mg_Head_BPM_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Time Signature event was found at bar 0. Defaulting to a 4/4 time signature..
        /// </summary>
        public static string Mg_Head_Time_Signature_event_not_found {
            get {
                return ResourceManager.GetString("Mg_Head_Time_Signature_event_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid joint type for {0}..
        /// </summary>
        public static string Mg_Invalid_joint_type_note {
            get {
                return ResourceManager.GetString("Mg_Invalid_joint_type_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodes in the original lengthy note having spacing less than 1/{1}..
        /// </summary>
        public static string Mg_Length_smaller_than_unit {
            get {
                return ResourceManager.GetString("Mg_Length_smaller_than_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no events found on main TIL {0}..
        /// </summary>
        public static string Mg_Main_timeline_not_found {
            get {
                return ResourceManager.GetString("Mg_Main_timeline_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; requires at least one argument..
        /// </summary>
        public static string Mg_Meta_Argument_count_min_one {
            get {
                return ResourceManager.GetString("Mg_Meta_Argument_count_min_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First argument must be a valid integer..
        /// </summary>
        public static string Mg_Meta_First_argument_must_int {
            get {
                return ResourceManager.GetString("Mg_Meta_First_argument_must_int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date format. Expected &apos;YYYYMMDD&apos;..
        /// </summary>
        public static string Mg_Meta_Invalid_date {
            get {
                return ResourceManager.GetString("Mg_Meta_Invalid_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown tag &apos;{0}&apos;..
        /// </summary>
        public static string Mg_Meta_Unknown_tag {
            get {
                return ResourceManager.GetString("Mg_Meta_Unknown_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SortName was provided. A new SortName has been generated from the Title..
        /// </summary>
        public static string Mg_No_sortname_provided {
            get {
                return ResourceManager.GetString("Mg_No_sortname_provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This note overlaps with note in other TILs. This may cause problems in the scroll speed of this note..
        /// </summary>
        public static string Mg_Note_overlapped_in_different_TIL {
            get {
                return ResourceManager.GetString("Mg_Note_overlapped_in_different_TIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to multiple overlapping Slide nodes existing simultaneously on this Air&apos;s position, it is unknown to determine from which Slide node the Air should start. Please try to space them apart in single ticks..
        /// </summary>
        public static string Mg_Overlapping_air_parent_slide {
            get {
                return ResourceManager.GetString("Mg_Overlapping_air_parent_slide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified StringID (id or str) {0} could not be found in &apos;{1}&apos;. Please check your input or run &quot;Recollect Game Assets&quot; to refresh the database. If you want to use your custom StringID, please provide both (i.e. &quot;#meta ... [ID] [String]&quot;)..
        /// </summary>
        public static string Mg_String_id_not_found {
            get {
                return ResourceManager.GetString("Mg_String_id_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown property mark {0} at file position 0x{1:X2}, data: {2}..
        /// </summary>
        public static string Mg_Unrecognized_meta {
            get {
                return ResourceManager.GetString("Mg_Unrecognized_meta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown note type {0} at file position 0x{1:X2}..
        /// </summary>
        public static string Mg_Unrecognized_note {
            get {
                return ResourceManager.GetString("Mg_Unrecognized_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent of Air cannot be null..
        /// </summary>
        public static string MgCrit_Air_parent_null {
            get {
                return ResourceManager.GetString("MgCrit_Air_parent_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent of AirSlide cannot be null..
        /// </summary>
        public static string MgCrit_Air_slide_parent_null {
            get {
                return ResourceManager.GetString("MgCrit_Air_slide_parent_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Hold is missing a tail..
        /// </summary>
        public static string MgCrit_Hold_has_no_tail {
            get {
                return ResourceManager.GetString("MgCrit_Hold_has_no_tail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified Air parent is invalid..
        /// </summary>
        public static string MgCrit_Invalid_Air_parent {
            get {
                return ResourceManager.GetString("MgCrit_Invalid_Air_parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified AirSlide parent is invalid..
        /// </summary>
        public static string MgCrit_Invalid_AirSlide_parent {
            get {
                return ResourceManager.GetString("MgCrit_Invalid_AirSlide_parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note are incompatible for pairing..
        /// </summary>
        public static string MgCrit_Pairing_notes_incompatible {
            get {
                return ResourceManager.GetString("MgCrit_Pairing_notes_incompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SoflanArea is missing a tail..
        /// </summary>
        public static string MgCrit_SoflanArea_has_no_tail {
            get {
                return ResourceManager.GetString("MgCrit_SoflanArea_has_no_tail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type {0} at file position 0x{1:X2}..
        /// </summary>
        public static string MgCrit_Unrecognized_data_type {
            get {
                return ResourceManager.GetString("MgCrit_Unrecognized_data_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown event mark {0} at file position0x{1:X2}..
        /// </summary>
        public static string MgCrit_Unrecognized_event {
            get {
                return ResourceManager.GetString("MgCrit_Unrecognized_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        public static string Status_Checked {
            get {
                return ResourceManager.GetString("Status_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting....
        /// </summary>
        public static string Status_collecting {
            get {
                return ResourceManager.GetString("Status_collecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting Background....
        /// </summary>
        public static string Status_Convert_background {
            get {
                return ResourceManager.GetString("Status_Convert_background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted.
        /// </summary>
        public static string Status_Converted {
            get {
                return ResourceManager.GetString("Status_Converted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting Audio....
        /// </summary>
        public static string Status_Converting_audio {
            get {
                return ResourceManager.GetString("Status_Converting_audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting Chart....
        /// </summary>
        public static string Status_Converting_chart {
            get {
                return ResourceManager.GetString("Status_Converting_chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting Jacket....
        /// </summary>
        public static string Status_Converting_jacket {
            get {
                return ResourceManager.GetString("Status_Converting_jacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Status_Done {
            get {
                return ResourceManager.GetString("Status_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Status_Error {
            get {
                return ResourceManager.GetString("Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting....
        /// </summary>
        public static string Status_Extracting {
            get {
                return ResourceManager.GetString("Status_Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string Status_Idle {
            get {
                return ResourceManager.GetString("Status_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading....
        /// </summary>
        public static string Status_Reading {
            get {
                return ResourceManager.GetString("Status_Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string Status_Saving {
            get {
                return ResourceManager.GetString("Status_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string Status_Searching {
            get {
                return ResourceManager.GetString("Status_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        public static string Status_Starting {
            get {
                return ResourceManager.GetString("Status_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating....
        /// </summary>
        public static string Status_Validate {
            get {
                return ResourceManager.GetString("Status_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing....
        /// </summary>
        public static string Status_Writing {
            get {
                return ResourceManager.GetString("Status_Writing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string Tab_Chart {
            get {
                return ResourceManager.GetString("Tab_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jacket.
        /// </summary>
        public static string Tab_Jacket {
            get {
                return ResourceManager.GetString("Tab_Jacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        public static string Tab_Misc {
            get {
                return ResourceManager.GetString("Tab_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string Tab_Music {
            get {
                return ResourceManager.GetString("Tab_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        public static string Tab_Option {
            get {
                return ResourceManager.GetString("Tab_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song.
        /// </summary>
        public static string Tab_Song {
            get {
                return ResourceManager.GetString("Tab_Song", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        public static string Tab_Stage {
            get {
                return ResourceManager.GetString("Tab_Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        public static string Title_Diagnostics {
            get {
                return ResourceManager.GetString("Title_Diagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the game folder.
        /// </summary>
        public static string Title_Select_the_game_folder {
            get {
                return ResourceManager.GetString("Title_Select_the_game_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the input file.
        /// </summary>
        public static string Title_Select_the_input_file {
            get {
                return ResourceManager.GetString("Title_Select_the_input_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the output folder.
        /// </summary>
        public static string Title_Select_the_output_folder {
            get {
                return ResourceManager.GetString("Title_Select_the_output_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Tick.
        /// </summary>
        public static string Unit_Tick {
            get {
                return ResourceManager.GetString("Unit_Tick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already the latest version.
        /// </summary>
        public static string Update_Already_Latest {
            get {
                return ResourceManager.GetString("Update_Already_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string Update_Checking {
            get {
                return ResourceManager.GetString("Update_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update check failed.
        /// </summary>
        public static string Update_Failed {
            get {
                return ResourceManager.GetString("Update_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version {0} available (Click to View).
        /// </summary>
        public static string Update_New_Version_Available {
            get {
                return ResourceManager.GetString("Update_New_Version_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to check for updates.
        /// </summary>
        public static string Update_Tooltip {
            get {
                return ResourceManager.GetString("Update_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple charts with the same song ID and difficulty exist, the last scanned file will be used..
        /// </summary>
        public static string Warn_Duplicate_id_and_difficulty {
            get {
                return ResourceManager.GetString("Warn_Duplicate_id_and_difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple charts for this Song ID have been tagged with “#meta main” in their comments. The first chart found with this tag will be set as the baseline difficulty..
        /// </summary>
        public static string Warn_More_than_one_chart_marked_main {
            get {
                return ResourceManager.GetString("Warn_More_than_one_chart_marked_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No baseline difficulty for this Song ID. Selecting the highest-difficulty chart by default. To choose a baseline difficulty explicitly, add `#meta main` to the comment of the chart..
        /// </summary>
        public static string Warn_No_chart_marked_main {
            get {
                return ResourceManager.GetString("Warn_No_chart_marked_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The preview start time is set later than 120 seconds. This may cause the game to freeze when selecting the song..
        /// </summary>
        public static string Warn_Preview_later_than_120 {
            get {
                return ResourceManager.GetString("Warn_Preview_later_than_120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage {0} with ID {1} already exists..
        /// </summary>
        public static string Warn_Stage_already_exists {
            get {
                return ResourceManager.GetString("Warn_Stage_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World&apos;s End chart must use unique Song ID; otherwise, other difficulty charts will not display under common song categories..
        /// </summary>
        public static string Warn_We_chart_must_be_unique_id {
            get {
                return ResourceManager.GetString("Warn_We_chart_must_be_unique_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string Window_Title {
            get {
                return ResourceManager.GetString("Window_Title", resourceCulture);
            }
        }
    }
}
